using System;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Uax14Net.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class LineBreakGenerator : IIncrementalGenerator
{
    private static readonly string[] Required =
    {
        "DerivedLineBreak.txt",
        "EastAsianWidth.txt",
        "emoji-data.txt",
        "DerivedGeneralCategory.txt"
    };

    private static readonly DiagnosticDescriptor MissingData = new(
        "UAX14001",
        "Unicode reference data not found",
        "Required Unicode data file '{0}' was not supplied as an AdditionalFile. Run reference/build.sh or reference/build.bat to download the Unicode 17.0.0 data.",
        "Uax14Net",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DataError = new(
        "UAX14002",
        "Unicode reference data could not be parsed",
        "The Unicode data could not be parsed: {0}",
        "Uax14Net",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var texts = context.AdditionalTextsProvider
            .Where(static t => IsRequired(t.Path))
            .Select(static (t, ct) => new NamedText(Path.GetFileName(t.Path), t.GetText(ct)?.ToString() ?? string.Empty))
            .Collect();

        context.RegisterSourceOutput(texts, static (spc, files) => Emit(spc, files));
    }

    private static bool IsRequired(string path)
    {
        string name = Path.GetFileName(path);
        foreach (string r in Required)
        {
            if (string.Equals(name, r, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }
        return false;
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<NamedText> files)
    {
        string? derivedLineBreak = Find(files, "DerivedLineBreak.txt");
        string? eastAsianWidth = Find(files, "EastAsianWidth.txt");
        string? emojiData = Find(files, "emoji-data.txt");
        string? generalCategory = Find(files, "DerivedGeneralCategory.txt");

        foreach (string name in Required)
        {
            if (Find(files, name) is null)
            {
                context.ReportDiagnostic(Diagnostic.Create(MissingData, Location.None, name));
                return;
            }
        }

        ushort[] values;
        try
        {
            values = UcdData.BuildValues(derivedLineBreak!, eastAsianWidth!, emojiData!, generalCategory!);
        }
        catch (Exception ex)
        {
            context.ReportDiagnostic(Diagnostic.Create(DataError, Location.None, ex.Message));
            return;
        }

        TrieResult trie = TrieBuilder.Build(values, new[] { 7, 8, 9, 10 });

        context.AddSource("LineBreakClass.g.cs", SourceText.From(EmitEnum(), Encoding.UTF8));
        context.AddSource("LineBreakData.g.cs", SourceText.From(EmitData(trie), Encoding.UTF8));
    }

    private static string? Find(ImmutableArray<NamedText> files, string name)
    {
        foreach (NamedText file in files)
        {
            if (string.Equals(file.Name, name, StringComparison.OrdinalIgnoreCase))
            {
                return file.Content;
            }
        }
        return null;
    }

    private static string EmitEnum()
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n#nullable enable\nnamespace Uax14Net;\n\npublic enum LineBreakClass : byte\n{\n");
        string[] canonical = UcdData.Canonical;
        for (int i = 0; i < canonical.Length; i++)
        {
            sb.Append("    ").Append(canonical[i]).Append(" = ").Append(i).Append(",\n");
        }
        sb.Append("}\n");
        return sb.ToString();
    }

    private static string EmitData(TrieResult trie)
    {
        int blockShift = trie.BlockShift;
        int blockMask = (1 << blockShift) - 1;
        int defaultValue = Array.IndexOf(UcdData.Canonical, "XX");

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n#nullable enable\n");
        sb.Append("using System;\nusing System.Runtime.CompilerServices;\nusing System.Runtime.InteropServices;\n\n");
        sb.Append("namespace Uax14Net;\n\n");
        sb.Append("internal static class LineBreakData\n{\n");
        sb.Append("    public const int BlockShift = ").Append(blockShift).Append(";\n");
        sb.Append("    public const int BlockMask = ").Append(blockMask).Append(";\n");
        sb.Append("    public const int MaxCodePoint = ").Append(UcdData.MaxCodePoint).Append(";\n\n");
        sb.Append("    public const byte FlagEastAsian = ").Append(UcdData.FlagEastAsian).Append(";\n");
        sb.Append("    public const byte FlagInitialPunctuation = ").Append(UcdData.FlagInitialPunctuation).Append(";\n");
        sb.Append("    public const byte FlagFinalPunctuation = ").Append(UcdData.FlagFinalPunctuation).Append(";\n");
        sb.Append("    public const byte FlagPictographicUnassigned = ").Append(UcdData.FlagPictographicUnassigned).Append(";\n");
        sb.Append("    public const byte FlagSaCombiningBase = ").Append(UcdData.FlagSaCombiningBase).Append(";\n\n");

        sb.Append("    [MethodImpl(MethodImplOptions.AggressiveInlining)]\n");
        sb.Append("    public static ushort Lookup(int codePoint)\n    {\n");
        sb.Append("        if ((uint)codePoint > MaxCodePoint)\n        {\n            return ").Append(defaultValue).Append(";\n        }\n");
        sb.Append("        ReadOnlySpan<ushort> stage1 = MemoryMarshal.Cast<byte, ushort>(Stage1);\n");
        sb.Append("        ReadOnlySpan<ushort> stage2 = MemoryMarshal.Cast<byte, ushort>(Stage2);\n");
        sb.Append("        int block = stage1[codePoint >> BlockShift];\n");
        sb.Append("        return stage2[(block << BlockShift) + (codePoint & BlockMask)];\n    }\n\n");

        sb.Append("    [MethodImpl(MethodImplOptions.AggressiveInlining)]\n");
        sb.Append("    public static LineBreakClass GetClass(int codePoint) => (LineBreakClass)(byte)Lookup(codePoint);\n\n");
        sb.Append("    [MethodImpl(MethodImplOptions.AggressiveInlining)]\n");
        sb.Append("    public static byte GetFlags(int codePoint) => (byte)(Lookup(codePoint) >> 8);\n\n");

        AppendByteSpan(sb, "Stage1", ToBytes(trie.Stage1));
        sb.Append('\n');
        AppendByteSpan(sb, "Stage2", ToBytes(trie.Stage2));

        sb.Append("}\n");
        return sb.ToString();
    }

    private static byte[] ToBytes(ushort[] values)
    {
        var bytes = new byte[values.Length * 2];
        for (int i = 0; i < values.Length; i++)
        {
            bytes[i * 2] = (byte)values[i];
            bytes[i * 2 + 1] = (byte)(values[i] >> 8);
        }
        return bytes;
    }

    private static void AppendByteSpan(StringBuilder sb, string name, byte[] data)
    {
        sb.Append("    private static ReadOnlySpan<byte> ").Append(name).Append(" => new byte[]\n    {\n        ");
        for (int i = 0; i < data.Length; i++)
        {
            sb.Append("0x").Append(data[i].ToString("X2")).Append(',');
            if ((i & 31) == 31)
            {
                sb.Append("\n        ");
            }
        }
        sb.Append("\n    };\n");
    }

    private readonly struct NamedText : IEquatable<NamedText>
    {
        public readonly string Name;
        public readonly string Content;

        public NamedText(string name, string content)
        {
            Name = name;
            Content = content;
        }

        public bool Equals(NamedText other)
            => string.Equals(Name, other.Name, StringComparison.Ordinal)
            && string.Equals(Content, other.Content, StringComparison.Ordinal);

        public override bool Equals(object? obj) => obj is NamedText other && Equals(other);

        public override int GetHashCode() => Name.GetHashCode() ^ Content.Length;
    }
}
